/* =====================================================================
   study-plan.js  -  the full week, exactly as the n8n Planner Agent
   produced it. This page renders; it does not plan.
   ===================================================================== */

const root = document.getElementById("root");

function priorityBlock(courses) {
  const ordered = [...(courses || [])].sort((a, b) => (a.priority || 99) - (b.priority || 99));
  if (!ordered.length) return "";

  const rows = ordered.map(c => `
    <tr>
      <td class="num"><strong>${UI.num(c.priority)}</strong></td>
      <td>
        <strong>${UI.esc(c.course_name)}</strong>
        <span class="faint"> ${UI.esc(c.course_code || "")}</span>
      </td>
      <td>${UI.riskPill(c.risk_level)}</td>
      <td class="num">${UI.num(c.recommended_weekly_hours, "0")}h</td>
      <td>${UI.esc(UI.deadlineText(c.next_deadline_in_days))}</td>
    </tr>`).join("");

  return `
  <div class="section-head"><h2>Academic priorities</h2></div>
  <div class="table-wrap">
    <table>
      <thead>
        <tr><th class="num">#</th><th>Course</th><th>Risk</th><th class="num">Hours</th><th>Next deadline</th></tr>
      </thead>
      <tbody>${rows}</tbody>
    </table>
  </div>`;
}

function render(data) {
  const days = UI.groupPlanByDay(data.study_plan);
  const planned = (data.study_plan || []).reduce((s, r) => s + Number(r.hours || 0), 0);
  const available = Number(data.available_weekly_study_hours) || 0;
  const spare = Math.round((available - planned) * 10) / 10;

  const body = days.length
    ? '<div class="plan-days">' + days.map(d => UI.planDayBlock(d, { showReason: true })).join("") + "</div>"
    : UI.emptyState("No study plan yet",
        "Once your courses have grades, the Planner Agent will build your week.",
        '<a class="btn btn-primary" href="add-course.html">+ Add Course</a>');

  root.innerHTML = `
    <div class="page-head">
      <h1>This Week's Study Plan</h1>
      <p>Generated by the Planner Agent from your risk levels, deadlines and available hours.</p>
    </div>

    <div class="summary">
      <div class="card">
        <span class="k">Available</span>
        <span class="v">${available}<small>h</small></span>
        <span class="s">Set on your profile</span>
      </div>
      <div class="card">
        <span class="k">Planned</span>
        <span class="v">${planned}<small>h</small></span>
        <span class="s">${spare === 0 ? "Fully allocated" : (spare > 0 ? spare + "h unallocated" : Math.abs(spare) + "h over budget")}</span>
      </div>
      <div class="card">
        <span class="k">Study days</span>
        <span class="v">${days.length}</span>
        <span class="s">In the coming week</span>
      </div>
      <div class="card">
        <span class="k">Sessions</span>
        <span class="v">${(data.study_plan || []).length}</span>
        <span class="s">Across ${(data.courses || []).length} courses</span>
      </div>
    </div>

    ${priorityBlock(data.courses)}

    <div class="section-head">
      <h2>Schedule</h2>
      <button class="btn btn-ghost btn-sm" id="refresh">Regenerate plan</button>
    </div>
    ${body}`;

  const btn = document.getElementById("refresh");
  if (btn) btn.addEventListener("click", () => start(true));
}

async function start(force) {
  root.innerHTML = '<div class="loading"><span class="spinner"></span> ' +
    (force ? "Rebuilding your study plan..." : "Loading your study plan...") + "</div>";
  try {
    render(await UI.Store.load(SESSION, { force: !!force }));
  } catch (err) {
    root.innerHTML = '<div class="form-msg error">' + UI.esc(err.message) + "</div>";
  }
}

start(false);
